[project]
name = "django-rest-framework-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.1",
    "djangorestframework>=3.16.1",
    "ipython>=9.9.0",
    "pygments>=2.19.2",
]
