[project]
name = "hello-django"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.1",
    "django-extensions>=4.1",
    "faker>=40.1.2",
]
